version: '3.8'

services:
  db:
    env_file: .env
    image: mysql
    container_name: gestion_recette
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3310:3306'

  app:
    env_file: .env
    image: api-recette
    container_name: recette-back-end
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - '3020:3020'
    depends_on:
      - db
volumes:
  db-data:
